<map id="pip._vendor.urllib3.exceptions.NewConnectionError" name="pip._vendor.urllib3.exceptions.NewConnectionError">
<area shape="rect" id="node1" title=" " alt="" coords="948,39,1169,80"/>
<area shape="rect" id="node2" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1ConnectTimeoutError.html" title=" " alt="" coords="679,5,900,47"/>
<area shape="rect" id="node3" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1TimeoutError.html" title=" " alt="" coords="409,8,631,49"/>
<area shape="rect" id="node4" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1HTTPError.html" title=" " alt="" coords="140,39,361,80"/>
<area shape="rect" id="node6" href="$classpip_1_1__vendor_1_1urllib3_1_1exceptions_1_1PoolError.html" title=" " alt="" coords="679,71,900,112"/>
<area shape="rect" id="node5" title=" " alt="" coords="5,46,92,73"/>
</map>
