\hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Hash\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1HashError}\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Hash\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpip_1_1__internal_1_1exceptions_1_1HashError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Hash\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=280pt]{classpip_1_1__internal_1_1exceptions_1_1HashError__coll__graph}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}{body}} (self)
\item 
\mbox{\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}} 
str {\bfseries \+\_\+\+\_\+str\+\_\+\+\_\+} (self)
\end{DoxyCompactItemize}
\doxysubsection*{Static Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a2943d28211010a8cd48570690695294b}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a2943d28211010a8cd48570690695294b}} 
string {\bfseries head} = \char`\"{}\char`\"{}
\item 
\mbox{\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a1d1b2323fec4165878134cdf6c385743}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a1d1b2323fec4165878134cdf6c385743}} 
{\bfseries int}
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}A failure to verify a package against known-good hashes

:cvar order: An int sorting hash exception classes by difficulty of
    recovery (lower being harder), so the user doesn't bother fretting
    about unpinned packages when he has deeper issues, like VCS
    dependencies, to deal with. Also keeps error reports in a
    deterministic order.
:cvar head: A section heading for display above potentially many
    exceptions of this kind
:ivar req: The InstallRequirement that triggered this error. This is
    pasted on after the exception is instantiated, because it's not
    typically available earlier.\end{DoxyVerb}
 

\doxysubsection{Member Function Documentation}
\mbox{\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}\label{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}} 
\index{pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}!body@{body}}
\index{body@{body}!pip.\_internal.exceptions.HashError@{pip.\_internal.exceptions.HashError}}
\doxysubsubsection{\texorpdfstring{body()}{body()}}
{\footnotesize\ttfamily  str pip.\+\_\+internal.\+exceptions.\+Hash\+Error.\+body (\begin{DoxyParamCaption}\item[{}]{self }\end{DoxyParamCaption})}

\begin{DoxyVerb}Return a summary of me for display under the heading.

This default implementation simply prints a description of the
triggering requirement.

:param req: The InstallRequirement that provoked this error, with
    its link already populated by the resolver's _populate_link().\end{DoxyVerb}
 

Reimplemented in \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a24c9ffc7b9a48c74ac53439d56a05dc6}{pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch}}, and \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMissing_afe037f000b99010da015d0209089d6dd}{pip.\+\_\+internal.\+exceptions.\+Hash\+Missing}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
