\hypertarget{classpip_1_1__internal_1_1exceptions_1_1PipError}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Pip\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1PipError}\index{pip.\_internal.exceptions.PipError@{pip.\_internal.exceptions.PipError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classpip_1_1__internal_1_1exceptions_1_1PipError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1PipError__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}The base pip error.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
