\hypertarget{classpip_1_1__internal_1_1exceptions_1_1UninstallationError}{}\doxysection{pip.\+\_\+internal.\+exceptions.\+Uninstallation\+Error Class Reference}
\label{classpip_1_1__internal_1_1exceptions_1_1UninstallationError}\index{pip.\_internal.exceptions.UninstallationError@{pip.\_internal.exceptions.UninstallationError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Uninstallation\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1UninstallationError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Uninstallation\+Error\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=217pt]{classpip_1_1__internal_1_1exceptions_1_1UninstallationError__coll__graph}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}General exception during uninstallation\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
inventaria\+\_\+env/lib/python3.\+10/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
